./"badger
.Dd 2022/8/19
.Dt rhino 1
.Os rhino(1)

.Sh NAME
.Nm rhino
.Nd rhino lib.

.Sh SYNOPSIS
.Nm
.Op Fl h Ar help
.Op Fl a Ar about
.Op Fl i Ar info.
.Op Fl w Ar welcome .

.Sh DESCRIPTION
.Nm
is a lib. 4 c++ & linux.
.Pp
* it's object oriented.

info.:
.Bl -tag -width -indent
.It "	author:			" "Badger Code".
.It "	date created:		" "2022/8/19".
.It "	version:			" "1".
.El

.Sh OPTIONS
.Bl -tag -width -indent
.It Fl h
help.
.It Fl a
about.
.It Fl i
info..
.It Fl w
welcome.
.El

.Sh AUTHOR
.Bl -tag -width -indent
.It author:
Badger Code.
.It github:
https://github.com/321BadgerCode.
.El

.Sh FILES
.Bl -tag -width -compact
.It program dir.:
.Pa /usr/local/bin/rhino.
.It man. dir.:
.Pa /usr/share/man/man1/rhino.1.gz.
.El